apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v1
  labels:
    version: v1
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: helloworld
        image: quay.io/dbais76/examples-helloworld-v2:latest
        resources:
          requests:
            cpu: "200m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
        

