apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- helloworld-ingress.yaml
- helloworld.yaml
resources:
- ../../base
configMapGenerator:
- literals:
  - k=v
  name: cm1
