apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hello-svc
  namespace: ansible-ocp
spec:
  host: hello-svc-ansible-ocp.apps.ocp4.example.com
  port:
    targetPort: 8080
  to:
    kind: Service
    name: hello-svc
    weight: 100
  wildcardPolicy: None

