- hosts: localhost
  tasks:
  - name: Try to login to OCP cluster
    redhat.openshift.openshift_auth:
      host: https://api.ocp4.example.com:6443
      username: admin
      password: redhat
      validate_certs: no
    register: k8s_auth_result

  - name: deploy hello-world pod
    k8s:
      state: present
      apply: yes
      namespace: ansible-ocp
      host: https://api.ocp4.example.com:6443 
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      validate_certs: no
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: hello-openshift
          labels:
            app: hello-openshift
        spec:
          selector:
            matchLabels:
              app: hello-openshift
          replicas: 1
          template:
            metadata:
              labels:
                app: hello-openshift
            spec:
              containers:
              - name: hello-openshift
                image: openshift/hello-openshift
                ports:
                - containerPort: 8080
                  protocol: TCP
                resources:
                  requests:
                    cpu: 300m
                    memory: 64Mi
                  limits:
                    cpu: 600m
                    memory: 128Mi

  - name: Expose web service port with ClusterIP
    k8s_service:
      state: present
      host: https://api.ocp4.example.com:6443
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      validate_certs: no
      namespace: ansible-ocp
      name: hello-svc
      ports:
      - port: 8080
        protocol: TCP
      selector:
        app: hello-openshift
  - name: Create a Route using the definition from a file
    k8s:
      state: present
      host: https://api.ocp4.example.com:6443
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      validate_certs: no
      src: /home/student/OCP-Demo/DO380/Ansible-OCP/hello-route.yaml
