- hosts: localhost
  tasks:
  - name: Try to login to OCP cluster
    redhat.openshift.openshift_auth:
      host: https://api.ocp4.example.com:6443
      username: admin
      password: redhat
      validate_certs: no
    register: k8s_auth_result


  - name: Get an existing Service object
    kubernetes.core.k8s_info:
      api_version: v1
      host: https://api.ocp4.example.com:6443
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      validate_certs: no  
      kind: Service
      name: hello-svc
      namespace: ansible-ocp
    register: web_service
  - name : display web_service
    debug:
     var: web_service
