apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: custom
spec:
  configuration:
  machineConfigSelector:
    matchLabels:
       machineconfiguration.openshift.io/role: custom
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/custom: ""
