apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: demoapp
    name: demoapp
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: quay.io/dbais76/fedora-httpd-ocp:1.0
      from:
        kind: DockerImage
        name: quay.io/dbais76/fedora-httpd-ocp:1.0
      generation: null
      importPolicy:
        importMode: Legacy
      name: "1.0"
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: demoapp
    name: demoapp
  spec:
    replicas: 1
    selector:
      app: demoapp
      deploymentconfig: demoapp
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: demoapp
          deploymentconfig: demoapp
      spec:
        containers:
        - image: quay.io/dbais76/fedora-httpd-ocp:1.0
          name: demoapp
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          volumeMounts:
          - mountPath: /var/www/html
            name: demoapp-vol
        volumes:
          - persistentVolumeClaim:
              claimName: demopvc
            name: demoapp-vol
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - demoapp
        from:
          kind: ImageStreamTag
          name: demoapp:1.0
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: demoapp
    name: demoapp
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: demoapp
      deploymentconfig: demoapp
  status:
    loadBalancer: {}
kind: List
metadata: {}
