- hosts: localhost
  tasks:
  - name: Try to login to OCP cluster
    redhat.openshift.openshift_auth:
      host: https://api.ocp4.example.com:6443
      username: admin
      password: redhat
      validate_certs: no
    register: k8s_auth_result

    
  - name: deploy hello-world pod
    redhat.openshift.k8s:
      state: present
      src: deployment.yaml
      namespace: ansible-ocp
      host: https://api.ocp4.example.com:6443 
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      validate_certs: no


  - name: create service using service inline definition
    k8s:
      state: present
      src: svc.yaml
      namespace: ansible-ocp
      host: https://api.ocp4.example.com:6443
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      validate_certs: no

  - name: create serviceaccount using service inline definition
    k8s:
      state: present
      src: ocpsa.yaml
      namespace: ansible-ocp
      host: https://api.ocp4.example.com:6443
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      validate_certs: no

  - name: Ensure infvormation about Pods is retrieved
    kubernetes.core.k8s_info:
      kind: Pod
      label_selectors:
        - app = hello-openshift
    register: pod_list
     
  - name: Create a Route exposing svc
    redhat.openshift.openshift_route:
      service: hello-svc
      host: https://api.ocp4.example.com:6443
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      namespace: ansible-ocp
      validate_certs: no
    register: route
  
  - name: Ensure the route is displayed
    debug:
      msg: "The application can be accessed using the url http://{{ route['result']['spec']['host'] }}"
